trading:
  commission: 0.003
  work-start-time: "10:00:00+03:00"
  work-duration: 540
  bot-enabled: false
  consecutive-empty-days-limit: 7

trend-reversal-decider:
  last-prices-count: 100
  extremum-price-index: 95

query.throttle:
  limit: 119
  interval: 60000

bot:
  delay: 60000
  tickers: SBER

spring.cache:
  cache-names: marketStocks, marketBonds, marketEtfs, marketCurrencies, marketCandles, marketInstrument
  scaffeine.spec: maximumSize=1000,expireAfterAccess=1h