trading:
  sandbox: false
  commission: 0.003
  work-start-time: 07:00:00+03:00
  work-duration: 720
  consecutive-empty-days-limit: 7
  start-date: 2000-01-01T00:00:00+03:00

golden-cross-strategy:
  configs:
    - small-window: 50
      big-window: 200
      index-coefficient: 0.8
    - small-window: 50
      big-window: 200
      index-coefficient: 0.7
    - small-window: 50
      big-window: 200
      index-coefficient: 0.6
    - small-window: 50
      big-window: 200
      index-coefficient: 0.5
    - small-window: 50
      big-window: 200
      index-coefficient: 0.4

simulation:
  thread-count: 100

query.throttle:
  interval: 60000
  limits:
    - segments:
        - sandbox
      limit: 120
    - segments:
        - portfolio
      limit: 120
    - segments:
        - market
      limit: 120
    - segments:
        - orders
      limit: 100
    - segments:
        - orders
        - limit-order
      limit: 50
    - segments:
        - orders
        - market-order
      limit: 50
    - segments:
        - orders
        - cancel
      limit: 50
    - segments:
        - operations
      limit: 120
    - segments:
        - md-openapi
        - ws
      limit: 1
  retry-interval: 5000
  attempts-count: 30
  default-limit: 120

bot:
  enabled: false
  delay: 60000
  tickers: SBER

spring.cache:
  cache-names: marketStocks, marketBonds, marketEtfs, marketCurrencies, marketCandles, marketInstrument
  scaffeine.spec: maximumSize=3000,expireAfterAccess=3h