scheduling:
  enabled: true

scheduled-bot:
  bot-configs:
    - account-id: 2000124699
      id: e6123145-9665-43e0-8413-cd61b8aa9b13
      candle-interval: CANDLE_INTERVAL_1_MIN
      commission: 0.003
      strategy-type: cross
      strategy-params:
        minimumProfit: 0.1
        movingAverageType: SMA
        order: 1
        smallWindow: 50
        bigWindow: 200
        indexCoefficient: 0.5
        greedy: true
    - broker-account-id: 2000124699
      id: USDRUB
      candle-interval: CANDLE_INTERVAL_1_MIN
      commission: 0.003
      strategy-type: conservative