trading:
  sandbox: true
  token: t.Kl5LYourgdH0sikBMvtbR-vhY4DCiwhexYK7kUED3L-_pirHWJ3qg2upAR2MJm5i1YGS6loyGWX7UZVPaFaqjQ

query.throttle:
  limit: 119
  interval: 60000

bot:
  delay: 60000
  tickers: SBER