trading:
  sandbox: false
  commission: 0.003
  work-start-time: 07:00:00+03:00
  work-duration: 720
  consecutive-empty-days-limit: 7
  start-date: 2000-01-01T00:00:00+03:00

scheduled-bot:
  delay: 60000
  enabled: false
  tickers: SBER
  candleResolution: 1min
  strategy-type: "simpleGoldenCross"
  strategy-params:
    minimumProfit: 0.1
    order: 1
    smallWindow: 50
    bigWindow: 200
    indexCoefficient: 0.5
    greedy: true

simulation:
  thread-count: 3

query.throttle:
  interval: 60000
  limits:
    - segments:
        - sandbox
      limit: 120
    - segments:
        - portfolio
      limit: 120
    - segments:
        - market
      limit: 120
    - segments:
        - orders
      limit: 100
    - segments:
        - orders
        - limit-order
      limit: 50
    - segments:
        - orders
        - market-order
      limit: 50
    - segments:
        - orders
        - cancel
      limit: 50
    - segments:
        - operations
      limit: 120
    - segments:
        - md-openapi
        - ws
      limit: 1
  retry-interval: 5000
  attempts-count: 30
  default-limit: 120

spring.cache:
  cache-names: marketStocks, marketBonds, marketEtfs, marketCurrencies, marketCandles, marketInstrument
  scaffeine.spec: maximumSize=3000,expireAfterAccess=3h