scheduling:
  enabled: true

scheduled-bot:
  bot-configs:
    - broker-account-id: "2000124699"
      ticker: SBER
      candle-resolution: 1min
      commission: 0.003
      strategy-type: "cross"
      strategy-params:
        minimumProfit: 0.1
        movingAverageType: SMA
        order: 1
        smallWindow: 50
        bigWindow: 200
        indexCoefficient: 0.5
        greedy: true
    - broker-account-id: "2000124699"
      ticker: USDRUB
      candle-resolution: 1min
      commission: 0.003
      strategy-type: "conservative"