trading:
  sandbox: false
  commission: 0.003
  work-start-time: 07:00:00+03:00
  work-duration: 720
  consecutive-empty-days-limit: 7
  start-date: 2000-01-01T00:00:00+03:00

trend-reversal-decider:
  configs:
    - extremum-price-index: 47
      last-prices-count: 50
    - extremum-price-index: 95
      last-prices-count: 100
    - extremum-price-index: 180
      last-prices-count: 200
    - extremum-price-index: 275
      last-prices-count: 300
    - extremum-price-index: 475
      last-prices-count: 500
    - extremum-price-index: 950
      last-prices-count: 1000

simulation:
  thread-count: 100

query.throttle:
  interval: 60000
  limits:
    - segments:
        - sandbox
      limit: 120
    - segments:
        - portfolio
      limit: 120
    - segments:
        - market
      limit: 120
    - segments:
        - orders
      limit: 100
    - segments:
        - orders
        - limit-order
      limit: 50
    - segments:
        - orders
        - market-order
      limit: 50
    - segments:
        - orders
        - cancel
      limit: 50
    - segments:
        - operations
      limit: 120
    - segments:
        - md-openapi
        - ws
      limit: 1
  retry-interval: 5000
  attempts-count: 30
  default-limit: 120

bot:
  enabled: false
  delay: 60000
  tickers: SBER

spring.cache:
  cache-names: marketStocks, marketBonds, marketEtfs, marketCurrencies, marketCandles, marketInstrument
  scaffeine.spec: maximumSize=3000,expireAfterAccess=3h