ru.tinkoff.invest.openapi:
  host: "https://api-invest.tinkoff.ru"

market:
  work-schedule:
    start-time: 07:00:00+03:00
    duration: 720

scheduling:
  delay: 60000
  enabled: false

scheduled-bot:
  bot-configs:
    - account-id: 2000124699
      figies: BBG004730N88
      candle-interval: CANDLE_INTERVAL_1_MIN
      commission: 0.003
      strategy-type: cross
      strategy-params:
        minimumProfit: 0.1
        movingAverageType: SMA
        order: 1
        smallWindow: 50
        bigWindow: 200
        indexCoefficient: 0.5
        greedy: true

back-test:
  thread-count: 4

spring:
  mvc.pathmatch.matching-strategy: ant_path_matcher
  cache:
    type: caffeine
    caffeine.spec: maximumSize=10000,expireAfterAccess=3h
    cache-names:
      exchange,
      instrument,
      share,
      allShares,
      allCurrencies,
      marketStocks,
      marketEtfs,
      marketCurrencies,
      marketCandles,
      tickerByFigi,
      firstPrice