trading:
  commission: 0.003
  work-start-time: "10:00:00+03:00"
  work-duration: 540
  bot-enabled: false

query.throttle:
  limit: 119
  interval: 60000

bot:
  delay: 60000
  tickers: SBER

spring.cache:
  cache-names: marketCandles, figi, instrument, instruments, marketInstrumentByTicker
  scaffeine.spec: maximumSize=1000,expireAfterAccess=1h