package ru.obukhov.trader.test.utils.model.share;

import ru.obukhov.trader.common.util.DecimalUtils;
import ru.obukhov.trader.market.model.Currencies;
import ru.obukhov.trader.market.model.Share;
import ru.obukhov.trader.test.utils.model.DateTimeTestData;
import ru.tinkoff.piapi.contract.v1.RealExchange;
import ru.tinkoff.piapi.contract.v1.SecurityTradingStatus;
import ru.tinkoff.piapi.contract.v1.ShareType;

public class TestShares {

    private static final Share APPLE_SHARE = Share.builder()
            .figi("BBG000B9XRY4")
            .ticker("AAPL")
            .classCode("SPBXM")
            .isin("US0378331005")
            .lot(1)
            .currency(Currencies.USD)
            .klong(DecimalUtils.setDefaultScale(2))
            .kshort(DecimalUtils.setDefaultScale(2))
            .dlong(DecimalUtils.ONE)
            .dshort(DecimalUtils.ONE)
            .dlongMin(DecimalUtils.ONE)
            .dshortMin(DecimalUtils.ONE)
            .shortEnabledFlag(false)
            .name("Apple")
            .exchange("SPB")
            .ipoDate(DateTimeTestData.newDateTime(1980, 12, 12))
            .issueSize(16530166000L)
            .countryOfRisk("US")
            .countryOfRiskName("Соединенные Штаты Америки")
            .sector("it")
            .issueSizePlan(50400000000L)
            .nominal(DecimalUtils.setDefaultScale(0.00001))
            .tradingStatus(SecurityTradingStatus.SECURITY_TRADING_STATUS_NORMAL_TRADING)
            .otcFlag(false)
            .buyAvailableFlag(true)
            .sellAvailableFlag(true)
            .divYieldFlag(true)
            .shareType(ShareType.SHARE_TYPE_COMMON)
            .minPriceIncrement(DecimalUtils.setDefaultScale(0.01))
            .apiTradeAvailableFlag(true)
            .uid("a9eb4238-eba9-488c-b102-b6140fd08e38")
            .realExchange(RealExchange.REAL_EXCHANGE_RTS)
            .positionUid("5c5e6656-c4d3-4391-a7ee-e81a76f1804e")
            .forIisFlag(true)
            .forQualInvestorFlag(true)
            .weekendFlag(false)
            .blockedTcaFlag(false)
            .first1MinCandleDate(DateTimeTestData.newDateTime(2018, 1, 10, 10, 34))
            .first1DayCandleDate(DateTimeTestData.newDateTime(1988, 9, 12, 3))
            .build();

    private static final Share SBER_SHARE = Share.builder()
            .figi("BBG004730N88")
            .ticker("SBER")
            .classCode("TQBR")
            .isin("RU0009029540")
            .lot(10)
            .currency(Currencies.RUB)
            .klong(DecimalUtils.setDefaultScale(2))
            .kshort(DecimalUtils.setDefaultScale(2))
            .dlong(DecimalUtils.setDefaultScale(0.2))
            .dshort(DecimalUtils.setDefaultScale(0.1999))
            .dlongMin(DecimalUtils.setDefaultScale(0.1056))
            .dshortMin(DecimalUtils.setDefaultScale(0.0954))
            .shortEnabledFlag(true)
            .name("Сбер Банк")
            .exchange("MOEX_EVENING_WEEKEND")
            .ipoDate(DateTimeTestData.newDateTime(2007, 7, 11))
            .issueSize(21586948000L)
            .countryOfRisk("RU")
            .countryOfRiskName("Российская Федерация")
            .sector("financial")
            .issueSizePlan(21586948000L)
            .nominal(DecimalUtils.setDefaultScale(3))
            .tradingStatus(SecurityTradingStatus.SECURITY_TRADING_STATUS_NORMAL_TRADING)
            .otcFlag(false)
            .buyAvailableFlag(true)
            .sellAvailableFlag(true)
            .divYieldFlag(true)
            .shareType(ShareType.SHARE_TYPE_COMMON)
            .minPriceIncrement(DecimalUtils.setDefaultScale(0.01))
            .apiTradeAvailableFlag(true)
            .uid("e6123145-9665-43e0-8413-cd61b8aa9b13")
            .realExchange(RealExchange.REAL_EXCHANGE_MOEX)
            .positionUid("41eb2102-5333-4713-bf15-72b204c4bf7")
            .forIisFlag(true)
            .forQualInvestorFlag(false)
            .weekendFlag(true)
            .blockedTcaFlag(false)
            .first1MinCandleDate(DateTimeTestData.newDateTime(2018, 3, 7, 21, 33))
            .first1DayCandleDate(DateTimeTestData.newDateTime(2000, 1, 4, 10))
            .build();

    private static final Share YANDEX_SHARE = Share.builder()
            .figi("BBG006L8G4H1")
            .ticker("YNDX")
            .classCode("TQBR")
            .isin("NL0009805522")
            .lot(1)
            .currency(Currencies.RUB)
            .klong(DecimalUtils.setDefaultScale(2))
            .kshort(DecimalUtils.setDefaultScale(2))
            .dlong(DecimalUtils.setDefaultScale(0.25))
            .dshort(DecimalUtils.setDefaultScale(0.2043))
            .dlongMin(DecimalUtils.setDefaultScale(0.134))
            .dshortMin(DecimalUtils.setDefaultScale(0.0974))
            .shortEnabledFlag(true)
            .name("Яндекс")
            .exchange("MOEX_PLUS")
            .ipoDate(DateTimeTestData.newDateTime(2011, 5, 24))
            .issueSize(326342270L)
            .countryOfRisk("RU")
            .countryOfRiskName("Российская Федерация")
            .sector("telecom")
            .issueSizePlan(0L)
            .nominal(DecimalUtils.setDefaultScale(0.01))
            .tradingStatus(SecurityTradingStatus.SECURITY_TRADING_STATUS_NORMAL_TRADING)
            .otcFlag(false)
            .buyAvailableFlag(true)
            .sellAvailableFlag(true)
            .divYieldFlag(false)
            .shareType(ShareType.SHARE_TYPE_COMMON)
            .minPriceIncrement(DecimalUtils.setDefaultScale(0.2))
            .apiTradeAvailableFlag(true)
            .uid("10e17a87-3bce-4a1f-9dfc-720396f98a3c")
            .realExchange(RealExchange.REAL_EXCHANGE_MOEX)
            .positionUid("cb51e157-1f73-4c62-baac-93f11755056a")
            .forIisFlag(true)
            .forQualInvestorFlag(false)
            .weekendFlag(true)
            .blockedTcaFlag(false)
            .first1MinCandleDate(DateTimeTestData.newDateTime(2018, 3, 7, 21, 38))
            .first1DayCandleDate(DateTimeTestData.newDateTime(2014, 6, 4, 10))
            .build();

    private static final Share DIOD_SHARE = Share.builder()
            .figi("BBG000R0L782")
            .ticker("DIOD")
            .classCode("TQBR")
            .isin("RU000A0JQWC1")
            .lot(100)
            .currency(Currencies.RUB)
            .klong(DecimalUtils.ZERO)
            .kshort(DecimalUtils.ZERO)
            .dlong(DecimalUtils.ZERO)
            .dshort(DecimalUtils.ZERO)
            .dlongMin(DecimalUtils.ZERO)
            .dshortMin(DecimalUtils.ZERO)
            .shortEnabledFlag(false)
            .name("ДИОД")
            .exchange("MOEX")
            .ipoDate(DateTimeTestData.newDateTime(2010, 1, 20))
            .issueSize(91500000L)
            .countryOfRisk("RU")
            .countryOfRiskName("Российская Федерация")
            .sector("health_care")
            .issueSizePlan(91500000L)
            .nominal(DecimalUtils.setDefaultScale(0.01))
            .tradingStatus(SecurityTradingStatus.SECURITY_TRADING_STATUS_NORMAL_TRADING)
            .otcFlag(false)
            .buyAvailableFlag(false)
            .sellAvailableFlag(true)
            .divYieldFlag(true)
            .shareType(ShareType.SHARE_TYPE_COMMON)
            .minPriceIncrement(DecimalUtils.setDefaultScale(0.01))
            .apiTradeAvailableFlag(false)
            .uid("464c9ca5-2ba5-4b66-90e2-005f30bff134")
            .realExchange(RealExchange.REAL_EXCHANGE_MOEX)
            .positionUid("4805aa22-7515-4a79-b4e7-cf02a41afcb7")
            .forIisFlag(true)
            .forQualInvestorFlag(false)
            .weekendFlag(false)
            .blockedTcaFlag(false)
            .first1MinCandleDate(DateTimeTestData.newDateTime(2019, 4, 4, 16, 30))
            .first1DayCandleDate(DateTimeTestData.newDateTime(1989, 5, 24, 3))
            .build();

    public static final TestShare APPLE = new TestShare(APPLE_SHARE);
    public static final TestShare SBER = new TestShare(SBER_SHARE);
    public static final TestShare YANDEX = new TestShare(YANDEX_SHARE);
    public static final TestShare DIOD = new TestShare(DIOD_SHARE);

}