package ru.obukhov.trader.test.utils.model.etf;

import ru.obukhov.trader.common.util.DecimalUtils;
import ru.obukhov.trader.market.model.Etf;
import ru.obukhov.trader.test.utils.model.DateTimeTestData;
import ru.tinkoff.piapi.contract.v1.RealExchange;
import ru.tinkoff.piapi.contract.v1.SecurityTradingStatus;

public class TestEtfs {

    private static final Etf FXIT_ETF = Etf.builder()
            .figi("BBG005HLTYH9")
            .ticker("FXIT")
            .classCode("TQTF")
            .isin("IE00BD3QJ757")
            .lot(1)
            .currency("rub")
            .klong(DecimalUtils.ZERO)
            .kshort(DecimalUtils.ZERO)
            .dlong(DecimalUtils.ZERO)
            .dshort(DecimalUtils.ZERO)
            .dlongMin(DecimalUtils.ZERO)
            .dshortMin(DecimalUtils.ZERO)
            .shortEnabledFlag(false)
            .name("FinEx Акции компаний IT-сектора США")
            .exchange("moex_close")
            .fixedCommission(DecimalUtils.setDefaultScale(0.9))
            .focusType("equity")
            .releasedDate(DateTimeTestData.newDateTime(2013, 10, 31, 3))
            .numShares(DecimalUtils.setDefaultScale(692000))
            .countryOfRisk("US")
            .countryOfRiskName("Соединенные Штаты Америки")
            .sector("it")
            .rebalancingFreq("quarterly")
            .tradingStatus(SecurityTradingStatus.SECURITY_TRADING_STATUS_NORMAL_TRADING)
            .otcFlag(false)
            .buyAvailableFlag(true)
            .sellAvailableFlag(true)
            .minPriceIncrement(DecimalUtils.ONE)
            .apiTradeAvailableFlag(true)
            .uid("232b3cca-ecef-439c-8e3c-bdd9e669f6e0")
            .realExchange(RealExchange.REAL_EXCHANGE_MOEX)
            .positionUid("ea43b22b-1568-4b16-b180-b70ae1d7f34a")
            .forIisFlag(true)
            .forQualInvestorFlag(true)
            .weekendFlag(false)
            .blockedTcaFlag(false)
            .first1MinCandleDate(DateTimeTestData.newDateTime(2018, 3, 7, 21, 35))
            .first1DayCandleDate(DateTimeTestData.newDateTime(2013, 10, 31, 3))
            .build();

    private static final Etf FXUS_ETF = Etf.builder()
            .figi("BBG005HLSZ23")
            .ticker("FXUS")
            .classCode("TQTF")
            .isin("IE00BD3QHZ91")
            .lot(1)
            .currency("rub")
            .klong(DecimalUtils.ZERO)
            .kshort(DecimalUtils.ZERO)
            .dlong(DecimalUtils.ZERO)
            .dshort(DecimalUtils.ZERO)
            .dlongMin(DecimalUtils.ZERO)
            .dshortMin(DecimalUtils.ZERO)
            .shortEnabledFlag(false)
            .name("FinEx Акции американских компаний")
            .exchange("moex_close")
            .fixedCommission(DecimalUtils.setDefaultScale(0.9))
            .focusType("equity")
            .releasedDate(DateTimeTestData.newDateTime(2013, 10, 31, 3))
            .numShares(DecimalUtils.setDefaultScale(330000))
            .countryOfRisk("US")
            .countryOfRiskName("Соединенные Штаты Америки")
            .sector("other")
            .rebalancingFreq("quarterly")
            .tradingStatus(SecurityTradingStatus.SECURITY_TRADING_STATUS_NORMAL_TRADING)
            .otcFlag(false)
            .buyAvailableFlag(true)
            .sellAvailableFlag(true)
            .minPriceIncrement(DecimalUtils.setDefaultScale(0.01))
            .apiTradeAvailableFlag(true)
            .uid("46a525d0-d33b-4100-a9d3-152045e5fef7")
            .realExchange(RealExchange.REAL_EXCHANGE_MOEX)
            .positionUid("37f20627-aef5-45f4-b184-e597ba3a28e5")
            .forIisFlag(true)
            .forQualInvestorFlag(true)
            .weekendFlag(false)
            .blockedTcaFlag(false)
            .first1MinCandleDate(DateTimeTestData.newDateTime(2018, 3, 7, 22, 17))
            .first1DayCandleDate(DateTimeTestData.newDateTime(2013, 10, 31, 3))
            .build();

    private static final Etf EZA_ETF = Etf.builder()
            .figi("BBG000PNJ9F5")
            .ticker("EZA")
            .classCode("SPBXM")
            .isin("US4642867802")
            .lot(1)
            .currency("usd")
            .klong(DecimalUtils.ZERO)
            .kshort(DecimalUtils.ZERO)
            .dlong(DecimalUtils.ZERO)
            .dshort(DecimalUtils.ZERO)
            .dlongMin(DecimalUtils.ZERO)
            .dshortMin(DecimalUtils.ZERO)
            .shortEnabledFlag(false)
            .name("iShares MSCI South Africa ETF")
            .exchange("spb_etf")
            .fixedCommission(DecimalUtils.setDefaultScale(0.64))
            .focusType("equity")
            .releasedDate(DateTimeTestData.newDateTime(2003, 2, 7, 3))
            .numShares(DecimalUtils.setDefaultScale(9600000))
            .countryOfRisk("ZA")
            .countryOfRiskName("Южно-Африканская Республика")
            .sector("")
            .rebalancingFreq("quarterly")
            .tradingStatus(SecurityTradingStatus.SECURITY_TRADING_STATUS_BREAK_IN_TRADING)
            .otcFlag(false)
            .buyAvailableFlag(true)
            .sellAvailableFlag(true)
            .minPriceIncrement(DecimalUtils.ONE)
            .apiTradeAvailableFlag(true)
            .uid("5375cdb7-4ad8-4139-aef1-6003dc331d07")
            .realExchange(RealExchange.REAL_EXCHANGE_RTS)
            .positionUid("76f544ad-ed9a-46a0-9b68-f28d961f0bff")
            .forIisFlag(true)
            .forQualInvestorFlag(true)
            .weekendFlag(false)
            .blockedTcaFlag(false)
            .first1MinCandleDate(DateTimeTestData.newDateTime(2022, 11, 11, 15, 30))
            .first1DayCandleDate(DateTimeTestData.newDateTime(2022, 11, 11, 10))
            .build();

    public static final TestEtf FXIT = new TestEtf(FXIT_ETF);
    public static final TestEtf FXUS = new TestEtf(FXUS_ETF);
    public static final TestEtf EZA = new TestEtf(EZA_ETF);

}